prg:
  url: https://www.americanexpress.com/us/credit-cards/card/premier-rewards-gold/
  search_term: Special Offer For You
green:
  url: https://www.americanexpress.com/us/credit-cards/card/green/
  search_term: Special Offer For You
plat:
  url: https://www.americanexpress.com/us/credit-cards/card/platinum/
  search_term: 100,000
everyday:
  url: https://www.americanexpress.com/us/credit-cards/card/amex-everyday/
  search_term: Earn 25,000 Membership Rewards
wait: 30